name    'inin-mssql2014'
version '0.3.0'
source  'https://github.com/PierrickI3/puppetlabs-mssql'
author  'Pierrick Lozach'
license 'Apache License 2.0'
summary 'Microsoft SQL Server 2014 Module'
description 'Microsoft SQL Server 2014 Installation Module for Puppet'
project_page 'https://github.com/puppetlabs/puppetlabs-mssql'

dependency 'puppetlabs/dism', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 3.1.0'
